- name: Copy app files to remote
  ansible.builtin.synchronize:
    src: "{{ app_src_dir }}/"
    dest: "{{ app_dest_dir }}/"
    recursive: yes

- name: Create app directory
  ansible.builtin.file:
    path: "{{ app_dest_dir }}"
    state: directory
    mode: '0755'
    recurse: yes

- name: Build Docker image
  community.docker.docker_image:
    name: "{{ app_image }}"
    build:
      path: "{{ app_dest_dir }}"
    source: build
  notify: restart app container

- name: Run container
  community.docker.docker_container:
    name: "{{ app_container }}"
    image: "{{ app_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ exposed_port }}:{{ container_port }}"

