---
- hosts: webservers
  become: true
  roles:
    - role: cleanup
      vars:
          docker_containers:
            - frontendapp
            - backendapp

          docker_images:
            - frontendapp
            - backendapp

          folders_to_delete:
            - /tmp/application

- hosts: frontend_vm
  become: true
  roles:
    - role: install_docker
    - role: application
      vars:
        app_name: frontendapp
        app_image: frontendapp
        app_container: frontendapp
        app_src_dir: ../ui
        app_dest_dir: /tmp/application
        exposed_port: 80
        container_port: 80

- hosts: frontend_vm
  become: true
  roles:
    - role: install_docker
    - role: application
      vars:
        app_name: frontendapp
        app_image: frontendapp
        app_container: frontendapp
        app_src_dir: ../ui
        app_dest_dir: /tmp/application
        exposed_port: 80
        container_port: 80

